ujs_ajax/config/routes.rb
Tester::Application.routes.draw do
  resources :posts
  
  scope :ujs, defaults: { format: :ujs } do
    post 'post_totals' => 'posts#totals'
  end

end

ujs_ajax/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    #render js: "alert('The number is: #{params[:id]}')"
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :ok }
    end
  end

  def totals
    value = 42
    render js: "$('#dashboard-totals').html('#{value}')"
  end
end

ujs_ajax/app/views/posts/_show.html.erb
Now you don't!

ujs_ajax/app/views/posts/index.html.erb
<%= link_to "Number Alert", post_path(42), remote: true %>

<div id="target-for-change">
  Now you see "ME"!
</div>

<br />
Dashboard totals: <span id="dashboard-totals">
<%= link_to ".", url_for({controller: "posts", action: "totals"}), method: :post, remote: true, class: "dashboard-totals" %>
</span>
<%= javascript_tag '$(".dashboard-totals").click();' %>

ujs_ajax/app/views/posts/show.js.erb
$("#target-for-change").html("<%= j render(partial: 'show') %>");